---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.7.4
_src_path: gh:kc-workspace/asdf-plugin-template.git
addon_yaml:
    archive: true
    checksum: true
    download: true
    fetch: true
    git: false
    github: true
    gpg: false
    help: true
    install: true
    package: false
    python: false
    system: true
    tags: true
    version: false
app_desc: A Kubernetes cluster resource sanitizer
app_name: popeye
app_repo: https://github.com/derailed/popeye
app_type: standalone
app_website: https://popeyecli.io
archive_conf_path: ''
archive_conf_strip: 0
archive_enabled: true
archive_regex: (\\.tar\\.gz|\\.tgz|\\.zip)$
checksum_conf_algorithm: 256
checksum_enabled: true
checksum_url: https://github.com/derailed/popeye/releases/download/v{version}/checksums.sha256
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_require_commands: ''
download_url: https://github.com/derailed/popeye/releases/download/v{version}/popeye_{os}_{arch}.tar.gz
gpg_enabled: false
install_map_enabled: true
install_map_method: move
install_map_yaml:
    popeye: bin/popeye
package_enabled: false
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-popeye
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-popeye.git
source_enabled: false
sys_arch_enabled: true
sys_arch_yaml:
    aarch64*: arm64
    armv5*: armv7
    armv6*: armv7
    armv7*: armv7
    i386: s390
    i686: s390
    powerpc64le: ppc64le
    ppc64le: ppc64le
    x86_64: amd64
sys_ext_enabled: false
sys_os_enabled: false
test_cmd_args: version
version_file_enabled: false
version_prefix: v
